/**
 * Single registry of stable application error codes.
 * User-facing copy lives in i18n only; codes are the contract.
 */

export const AUTH_ERROR_CODE = Object.freeze({
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
  EMAIL_ALREADY_EXISTS: "EMAIL_ALREADY_EXISTS",
  WEAK_PASSWORD: "WEAK_PASSWORD",
  INVALID_EMAIL: "INVALID_EMAIL",
  AUTHENTICATION_ERROR: "AUTHENTICATION_ERROR",
  AUTH_PROVIDER_SERVER_ERROR: "AUTH_PROVIDER_SERVER_ERROR",
  EMAIL_VERIFICATION_ERROR: "EMAIL_VERIFICATION_ERROR",
  PASSWORD_RESET_ERROR: "PASSWORD_RESET_ERROR",
  INVALID_TOKEN: "INVALID_TOKEN",
  SAME_PASSWORD: "SAME_PASSWORD",
  PASSWORD_UPDATE_NOT_ALLOWED: "PASSWORD_UPDATE_NOT_ALLOWED",
} as const);

export const DOMAIN_RULE_ERROR_CODE = Object.freeze({
  TICKET_PROJECT_MISMATCH: "TICKET_PROJECT_MISMATCH",
  LAST_ADMIN_REQUIRED: "LAST_ADMIN_REQUIRED",
  MEMBER_ROLE_CHANGE_ADMIN_REQUIRED: "MEMBER_ROLE_CHANGE_ADMIN_REQUIRED",
  INVITATION_ALREADY_USED: "INVITATION_ALREADY_USED",
  INVITATION_EXPIRED: "INVITATION_EXPIRED",
  INVITATION_ALREADY_MEMBER: "INVITATION_ALREADY_MEMBER",
  INVITATION_LIMIT_REACHED: "INVITATION_LIMIT_REACHED",
  INVALID_COLUMN_ORDER: "INVALID_COLUMN_ORDER",
  DUPLICATE_COLUMN_KEY: "DUPLICATE_COLUMN_KEY",
  INVALID_BOARD_COLUMN_RELATIONSHIP: "INVALID_BOARD_COLUMN_RELATIONSHIP",
  MIXED_BOARD_COLUMNS: "MIXED_BOARD_COLUMNS",
  MISSING_DONE_COLUMN: "MISSING_DONE_COLUMN",
  COLUMN_IN_USE: "COLUMN_IN_USE",
  UPDATE_CREDENTIALS_NO_FIELDS: "UPDATE_CREDENTIALS_NO_FIELDS",
} as const);

export const REPOSITORY_ERROR_CODE = Object.freeze({
  NOT_FOUND: "NOT_FOUND",
  CONSTRAINT_VIOLATION: "CONSTRAINT_VIOLATION",
  DATABASE_ERROR: "DATABASE_ERROR",
} as const);

export type DomainRuleErrorCode =
  (typeof DOMAIN_RULE_ERROR_CODE)[keyof typeof DOMAIN_RULE_ERROR_CODE];

export const DOMAIN_RULE_ERROR_CODES = Object.freeze(
  Object.values(DOMAIN_RULE_ERROR_CODE) as DomainRuleErrorCode[]
);

/**
 * Infrastructure and product-level errors (non-auth, non-domain-rule).
 */
export const INFRA_ERROR_CODE = Object.freeze({
  AVATAR_FILE_TOO_LARGE: "AVATAR_FILE_TOO_LARGE",
  AVATAR_INVALID_MIME_TYPE: "AVATAR_INVALID_MIME_TYPE",
  AVATAR_PROCESSING_FAILED: "AVATAR_PROCESSING_FAILED",
  STRIPE_PRICE_NOT_CONFIGURED: "STRIPE_PRICE_NOT_CONFIGURED",
  STRIPE_CHECKOUT_NO_URL: "STRIPE_CHECKOUT_NO_URL",
  STRIPE_WEBHOOK_NOT_CONFIGURED: "STRIPE_WEBHOOK_NOT_CONFIGURED",
  BILLING_NO_CUSTOMER: "BILLING_NO_CUSTOMER",
  BOARD_INVALID_COLUMN_WORKFLOW_STATE: "BOARD_INVALID_COLUMN_WORKFLOW_STATE",
  GOOGLE_OAUTH_NOT_AVAILABLE: "GOOGLE_OAUTH_NOT_AVAILABLE",
  DELETE_ACCOUNT_FAILED: "DELETE_ACCOUNT_FAILED",
} as const);

export const APP_ERROR_CODE = Object.freeze({
  ...AUTH_ERROR_CODE,
  ...DOMAIN_RULE_ERROR_CODE,
  ...REPOSITORY_ERROR_CODE,
  ...INFRA_ERROR_CODE,
} as const);

export type AppErrorCode = (typeof APP_ERROR_CODE)[keyof typeof APP_ERROR_CODE];

export const APP_ERROR_CODES = Object.freeze(
  Object.values(APP_ERROR_CODE) as AppErrorCode[]
);

export type AuthErrorCode =
  (typeof AUTH_ERROR_CODE)[keyof typeof AUTH_ERROR_CODE];

export const AUTH_ERROR_CODES = Object.freeze(
  Object.values(AUTH_ERROR_CODE) as AuthErrorCode[]
);

export type RepositoryErrorCode =
  (typeof REPOSITORY_ERROR_CODE)[keyof typeof REPOSITORY_ERROR_CODE];

export const REPOSITORY_ERROR_CODES = Object.freeze(
  Object.values(REPOSITORY_ERROR_CODE) as RepositoryErrorCode[]
);
