export const BOARD_COLUMN_DROP_PREFIX = "column:";
export const BOARD_MOUSE_DRAG_ACTIVATION_DISTANCE_PX = 4;
export const BOARD_TOUCH_DRAG_ACTIVATION_DELAY_MS = 150;
export const BOARD_TOUCH_DRAG_ACTIVATION_TOLERANCE_PX = 8;
